version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=ubcsolar
      - DOCKER_INFLUXDB_INIT_ORG=UBC Solar
      - DOCKER_INFLUXDB_INIT_BUCKET=Telemetry
    restart: unless-stopped

volumes:
  grafana:
  influxdb-storage:
  influxdb-config:
