version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - type: bind
        source: ./plugins
        target: /var/lib/grafana/plugins

    restart: always
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mqtt-datasource

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=ubcsolar
      - DOCKER_INFLUXDB_INIT_ORG=UBC Solar
      - DOCKER_INFLUXDB_INIT_BUCKET=Telemetry
    restart: always

volumes:
  grafana:
  influxdb-storage:
  influxdb-config:
